[package]
name = "poseidon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
poseidon-base = { git = "https://github.com/scroll-tech/poseidon-circuit", branch = "main" }
ff = "0.13"
bytemuck = "1.16.0"

